// Render the weekly digest and open one GitHub issue for it, then mark every
// candidate from this run as seen so nothing re-surfaces next week.
// Set DRY_RUN=1 to print the digest instead of creating an issue.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dryRun = process.env.DRY_RUN === '1';

const candidates = JSON.parse(await readFile(join(root, 'candidates.json'), 'utf8'));
const { picks = [] } = JSON.parse(await readFile(join(root, 'triage.json'), 'utf8'));

const today = new Date().toISOString().slice(0, 10);

const SECTIONS = [
  { impact: 'breaking', heading: '🔴 Breaking risk' },
  { impact: 'opportunity', heading: '🟢 Opportunities' },
  { impact: 'watch', heading: '👀 Worth watching' },
];

function render() {
  if (picks.length === 0) return null;

  const lines = [`Browser-platform changes the SDK team may care about. Triaged from ${candidates.length} new item(s) this week.`, ''];

  for (const { impact, heading } of SECTIONS) {
    const group = picks.filter(p => p.impact === impact);
    if (group.length === 0) continue;
    lines.push(`## ${heading}`, '');
    for (const p of group) {
      lines.push(`### [${p.title}](${p.url})`);
      lines.push(`\`${p.source}\` · urgency: **${p.urgency}**`);
      lines.push('');
      lines.push(p.why);
      lines.push('');
    }
  }

  lines.push('---', '_Generated by browser-updates-radar. Edit `prompts/interest-profile.md` to tune what gets surfaced, and `sources.config.mjs` to add sources._');
  return lines.join('\n');
}

async function markSeen() {
  const path = join(root, 'state/seen.json');
  let seen = [];
  try {
    seen = JSON.parse(await readFile(path, 'utf8'));
  } catch {
    /* first run */
  }
  const set = new Set(seen);
  for (const c of candidates) set.add(`${c.source}:${c.id}`);
  await writeFile(path, JSON.stringify([...set], null, 2));
  console.log(`seen.json now tracks ${set.size} item(s).`);
}

const body = render();
const title = `Browser Updates Radar — week of ${today}`;

// Dry run: show what would be published and leave all persistent state alone.
// Crucially we do NOT markSeen() here — otherwise a dry run would silently
// suppress these items from the next real run.
if (dryRun) {
  if (!body) console.log('Nothing notable this week — no issue would be created.');
  else console.log(`\n=== ${title} ===\n\n${body}`);
  console.log('\n(dry run — no issue created, state/seen.json left unchanged)');
  process.exit(0);
}

if (!body) {
  console.log('Nothing notable this week — no issue created.');
  await markSeen();
  process.exit(0);
}

const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN;
const repo = process.env.GITHUB_REPOSITORY;
if (!token || !repo) {
  console.error('GH_TOKEN/GITHUB_TOKEN and GITHUB_REPOSITORY must be set to create an issue.');
  process.exit(1);
}

const res = await fetch(`https://api.github.com/repos/${repo}/issues`, {
  method: 'POST',
  headers: {
    authorization: `Bearer ${token}`,
    accept: 'application/vnd.github+json',
    'content-type': 'application/json',
    'user-agent': 'browser-updates-radar',
  },
  body: JSON.stringify({ title, body, labels: ['browser-radar'] }),
});

if (!res.ok) {
  console.error(`Failed to create issue ${res.status}: ${await res.text()}`);
  process.exit(1);
}

const issue = await res.json();
console.log(`Created issue #${issue.number}: ${issue.html_url}`);
await markSeen();
